### PR TITLE
creation of test suite for `pkg/ipns`

### LINKED ISSUE #648: Fix pkg/ipns tests and make them CI Run-able
Needs an IPFS local shell

### PR DESCRIPTION
**Pull request by joshLong145**
- removes test case from `ipns` that would always fail due to the given `cid` not being present. 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by ntindle** [comment]
Should this just upload something in a setup?

**Comment by joshLong145** [comment]
> Should this just upload something in a setup?

the module isnt being used in any part of sonr at this time. when the module is brought in for creating persistent address it can be tested. this is being removed now to no longer fail the test suite.

**Comment by joshLong145** [comment]
> Should this just upload something in a setup?

Added it to a suite so an `document` is created and uploaded with a cid

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
Closes #648

**Review by mcjcloud — APPROVED** [review]

**Pull request merged**
