### PR TITLE
Update/GitHub actions motor

### PR DESCRIPTION
**Pull request by prdlk**
Our CI/CD needed an upgrade, we havent refactored since disabling goreleaser.

## Changes

* Release workflow builds Motor for ios, android, web
* Introduced script to automatically generate an image for new release using [placid](https://placid.app)
* Introduced Announce action to publish to twitter post release
* New Nightly workflow to run cron builds on dev branch
* Refactored `scripts/bind.sh` to include version, outpath, and platform

## Checklist

* [ X ] Unit tests
* [ X ] Documentation

 Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

### CODE REVIEW

**Review by ntindle — APPROVED** [review]
May as well add the brew stuff to this yolo

**Comment by prdlk** [comment]
> May as well add the brew stuff to this yolo

Thats for Speedway doesnt make sense for this repo to have goreleaser really

**Comment by ntindle** [comment]
I simply need a nap

**Review by 6missedcalls — APPROVED** [review]
LGTM - nice emojis

**Pull request merged**
