### PR TITLE
ci: update to go version 1.17 from 1.16

### PR DESCRIPTION
**Pull request by joshLong145**
<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by ntindle** [comment]
How does this effect things?

**Comment by Peyton232** [comment]
> How does this effect things?

1.17 involved mostly enhancments to the language and does not feature any breaking changes. I've been running locally on 1.17 for a while now. We are more likely to break things if we went back a version rather than upgrading.
Overall this release added functionality in a backwards compatible manner. 

changelog if you want a more detailed answer - https://go.dev/doc/go1.17

**Comment by joshLong145** [comment]
Can we get this merged soon? Need this mod upgrade for core modules

**Comment by Peyton232** [comment]
@joshLong145 change destination to dev so we can approve

**Comment by Peyton232** [comment]
@joshLong145 change destination to dev so we can approve

**Comment by joshLong145** [comment]
On it

**Comment by joshLong145** [comment]
branch is now pointed at release, once approved it will be merged.

**Review by Peyton232 — APPROVED** [review]

**Pull request merged**
