### PR TITLE
Disable signature verification [BLOK-113]

### PR DESCRIPTION
**Pull request by mcjcloud**
Temporarily disables sig verification on chain

 Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

### CODE REVIEW

**Comment by prdlk** [comment]
Automatically moved to [Linear (#113)](https://linear.app/sonr-io/issue/BLOK-113/disable-signature-verification-sonr-iosonr-756)

---
*via LinearSync*

**Comment by mcjcloud** [comment]
@prnk28 Why is this closed?

**Comment by prdlk** [comment]
Think it was linear triage issue

**Comment by prdlk** [comment]
@mcjcloud up now!

**Review by joshLong145 — APPROVED** [review]

**Review by prdlk — APPROVED** [review]

**Pull request merged**
