### PR TITLE
Integrate/motor cicd

### LINKED ISSUE #261: Build CI/CD pipeline to deploy frontend packages to registries
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202534122718799) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by prdlk**
## Changes

* Embed gomobile library into motor-lib for binding to frameworks
* Implement CI/CD for gomobile for motor node ios, android

 Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

### CODE REVIEW

**Review by joshLong145 — DISMISSED** [review]
changes to host and highway look good. @ntindle can you verify the deploy scripts?

**Comment by ntindle** [comment]
MacOS runners cost 10x (literally) the amount of linux if we run out of minutes, would really love if we could run linux for this

**Review by joshLong145 — APPROVED** [review]
Looks good from the host side, the unicode in the shell scripts worry me a bit as some machines / terminals might error on attempt to render this.

**Comment by prdlk** [comment]
If it's running in github actions it should be good - one thing to note probably best to migrate off macos only runner in the future

**Pull request merged**
