### PR TITLE
Feat/schema service in who is

### PR DESCRIPTION
**Pull request by joshLong145**
- addition of service endpoint in `WhoIs` `DIDDocument` to register a `WhatIs` did as a service.
## Changes

- Item 1
- Item 2

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by mcjcloud** [comment]
What does it mean to add a WhatIs as a service?

**Comment by ntindle** [comment]
> What does it mean to add a WhatIs as a service?

+1

**Comment by joshLong145** [comment]
This is a way of associating schemas with a whoIs instance. This allows the sdk to query schema with our explicit calls by the developer. For purposes of caching within the sdk for later queries

**Comment by prnk28** [comment]
We need IPNS this is further bandaid for bandaid

**Comment by ntindle** [comment]
> This is a way of associating schemas with a whoIs instance. This allows the sdk to query schema with our explicit calls by the developer. For purposes of caching within the sdk for later queries

I’m sorry, this doesn’t make any sense to me. Can you give an example of the use?

**Comment by joshLong145** [comment]
> > This is a way of associating schemas with a whoIs instance. This allows the sdk to query schema with our explicit calls by the developer. For purposes of caching within the sdk for later queries
> 
> I’m sorry, this doesn’t make any sense to me. Can you give an example of the use?

with these service endpoints for schemas, sdk implementations can now  pre initialize content by querying for it whenever they choose, such that its is available before invoking an explicit query command. or to put it simply  pre fetching content.

**Comment by joshLong145** [comment]
converted to a draft as im seeing issues with accessing key value stores from the registry keeper from the schema module context. looking into it.

**Comment by mcjcloud** [comment]
Okay the rationale makes sense. Is this work being tracked?

**Pull request closed without merging**
