### PR TITLE
Merge Pradsnr/blok 13

### PR DESCRIPTION
**Pull request by prdlk**
Rescaffolded the Bucket module to allow for upgraded changes. Note - this is simply for scaffolding the skeleton module, implementation of methods and connecting ipfs are separate tasks.

## Changes

* See Design Doc on Linear for Reference

 Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

### CODE REVIEW

**Comment by lakshya-sky** [comment]
Looks okay. But how do we maintain access control and visibility? since everything we store on the block-chain could be retrieved one way or another.

**Review by lakshya-sky — APPROVED** [review]

**Review by ntindle — APPROVED** [review]
Approved without review. Theres a huge amount of changes here and it fails a large number of CI and tests

**Comment by prdlk** [comment]
> Looks okay. But how do we maintain access control and visibility? since everything we store on the block-chain could be retrieved one way or another.

Checkout https://docs.textile.io/buckets/

**Comment by prdlk** [comment]
> Approved without review. Theres a huge amount of changes here and it fails a large number of CI and tests

See the error messages from CI Tests, its because the type names have changed and accompanying tests arent written.

**Pull request merged**
