### PR TITLE
fixed dev

### PR DESCRIPTION
**Pull request by mcjcloud**
Fixes issue preventing highway from starting

Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529397805053) by [Unito](https://www.unito.io)
┆Attachments: #387 fixed dev

### CODE REVIEW

**Review by joshLong145 — APPROVED** [review]

**Comment by ntindle** [comment]
Do we know why this failed ci?

**Comment by prdlk** [comment]
Build is not passing

**Comment by joshLong145** [comment]
chain doesnt seem to build with the libp2p target changes for some reason. looks like missing module implementations

**Review by ntindle — APPROVED** [review]

**Review by 6missedcalls — APPROVED** [review]
LGTM

**Review by prdlk — APPROVED** [review]

**Comment by prdlk** [comment]
God damn it

**Comment by prdlk** [comment]
Whats good with this??

**Pull request closed without merging**
