### PR TITLE
Migrate repos into a monorepo

### PR DESCRIPTION
**Pull request by mcjcloud**
Combine blockchain, core, and highway-sdk into a single repo, using https://github.com/golang-standards/project-layout as a reference.

## Changes

- See https://www.notion.so/sonr/Monorepo-Migration-509bd03aee6f45d1b397554fa14fd2a2 for file structure

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by ntindle** [comment]
Where is the highway being served from?

**Comment by ntindle** [comment]
Also may be missing it but I don't see most of the chain related stuff anymore

**Comment by joshLong145** [comment]
I dont think we want to use sub modules. I think using go module format is the way we want to move forward, which keeps us a bit more generic.

**Comment by mcjcloud** [comment]
> I dont think we want to use sub modules. I think using go module format is the way we want to move forward, which keeps us a bit more generic.

This was done by mistake, will figure out how to revert

**Comment by ntindle** [comment]
May want to rewrite readme

**Comment by prdlk** [comment]
Oh baby this is it isnt it

**Comment by ntindle** [comment]
This looks like it stands up but I can't get the endpoints to work. 

~Getting 404 not found on all endpoints~
NVM I can't type

**Comment by ntindle** [comment]
Looks like blob remove doesn't work for real though

**Review by ntindle — DISMISSED** [review]

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
LGTM, swagger taskfile needs updated to output to the correct directory

**Pull request merged**
