### PR TITLE
Enable test verification in CI

### PR DESCRIPTION
**Pull request by ntindle**
## Changes

* Removes the auto pass for testing and coverage

## API Updates

N/A

### New Features *(required)*

N/A

### Deprecations *(required)*

N/A

### Enhancements *(optional)*

Your tests must now pass.

## Checklist

* [x] Unit tests
* [x] Documentation

## References *(optional)*

Fixes
Connects

Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529469827894) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by ntindle** [comment]
@joshLong145 Do you know why this failed?

**Comment by joshLong145** [comment]
> @joshLong145 Do you know why this failed?

@ntindle Appears to be an issue with the matrix server configuration options not working in ci. this is from the call stack in the builder

**Comment by ntindle** [comment]
Are you saying it's dependent on the app.env?

**Comment by joshLong145** [comment]
> Are you saying it's dependent on the app.env?

perhaps, what im saying is the matrix implementation is throwing errors due to some nil properties it needs to stand up properly. See the stack trace below from the action logs:
```
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/setup/jetstream/nats.go:32:4: unknown field 'DontListen' in struct literal of type server.Options
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/setup/jetstream/nats.go:57:36: undefined: nats.InProcessServer
# github.com/matrix-org/dendrite/syncapi/storage/postgres
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/account_data_table.go:110:71: cannot use accountDataEventFilter.Types (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/account_data_table.go:111:71: cannot use accountDataEventFilter.NotTypes (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/current_room_state_table.go:237:17: cannot convert stateFilter.Senders (type *[]string) to type pq.StringArray
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/current_room_state_table.go:238:17: cannot convert stateFilter.NotSenders (type *[]string) to type pq.StringArray
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/current_room_state_table.go:239:60: cannot use stateFilter.Types (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/current_room_state_table.go:240:60: cannot use stateFilter.NotTypes (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/output_room_events_table.go:[21](https://github.com/sonr-io/sonr/runs/6527129257?check_suite_focus=true#step:7:22)0:17: cannot convert stateFilter.Senders (type *[]string) to type pq.StringArray
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/output_room_events_table.go:211:17: cannot convert stateFilter.NotSenders (type *[]string) to type pq.StringArray
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/output_room_events_table.go:212:60: cannot use stateFilter.Types (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/output_room_events_table.go:213:60: cannot use stateFilter.NotTypes (type *[]string) as type []string in argument to filterConvertTypeWildcardToSQL
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/postgres/output_room_events_table.go:213:60: too many errors
# github.com/matrix-org/dendrite/syncapi/storage/sqlite3
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/account_data_table.go:1[22](https://github.com/sonr-io/sonr/runs/6527129257?check_suite_focus=true#step:7:23):25: cannot range over accountDataFilterPart.Types (type *[]string)
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/account_data_table.go:127:25: cannot range over accountDataFilterPart.NotTypes (type *[]string)
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/current_room_state_table.go:221:14: cannot use stateFilter.Senders (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/current_room_state_table.go:221:35: cannot use stateFilter.NotSenders (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/current_room_state_table.go:222:14: cannot use stateFilter.Types (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/current_room_state_table.go:222:33: cannot use stateFilter.NotTypes (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/output_room_events_table.go:171:14: cannot use stateFilter.Senders (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/output_room_events_table.go:171:35: cannot use stateFilter.NotSenders (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/output_room_events_table.go:172:14: cannot use stateFilter.Types (type *[]string) as type []string in argument to prepareWithFilters
Error: ../../../go/pkg/mod/github.com/matrix-org/dendrite@v0.8.1/syncapi/storage/sqlite3/output_room_events_table.go:172:[33](https://github.com/sonr-io/sonr/runs/6527129257?check_suite_focus=true#step:7:34): cannot use stateFilter.NotTypes (type *[]string) as type []string in argument to prepareWithFilters
```

**Comment by prdlk** [comment]
Is this still relevant?

**Comment by ntindle** [comment]
Yes, we just need to get tests passing for it to mean anything

**Comment by prdlk** [comment]
Lmao @ntindle just saw the commit history its just updating from dev to wait for the tests to pass XD

**Pull request closed without merging**
