### PR TITLE
reduction to number of device shards generated.

### PR DESCRIPTION
**Pull request by joshLong145**
- reduces device shards down to three
## Changes

- Item 1
- Item 2

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Review by mcjcloud — APPROVED** [review]
lgtm

**Comment by ntindle** [comment]
Is there anywhere that checks this or requires x number of shards on the vault side? @mcjcloud

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
Have we benchmarked this? May be worth pushing into calhard

**Comment by joshLong145** [comment]
> Is there anywhere that checks this or requires x number of shards on the vault side? @mcjcloud

the checks are on if there are device shards left not any specific amount.

**Pull request merged**
