### PR TITLE
Add Simulation Tests to the pipeline

### PR DESCRIPTION
**Pull request by ntindle**
Runs the simulation as part of your PR

## Changes

* Item 1
* Item 2

## Checklist

* [ ] Unit tests
* [ ] Documentation

## References *(optional)*

Fixes
Connects

Mention [stepsize] in a comment if you'd like to report some technical debt. See examples here.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202528620406598/1202529368720196) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by joshLong145 — APPROVED** [review]

**Comment by mcjcloud** [comment]
Is this PR still relevant?

**Comment by prdlk** [comment]
Yo yo is anyone home?

**Review by 6missedcalls — APPROVED** [review]
LGTM

**Comment by joshLong145** [comment]
before merging are all simulations running currently? i think 'registry' is still broken

**Comment by ntindle** [comment]
No they aren't all working but at least theyre running

**Pull request merged**
